### ISSUE TITLE
Items from a Chest to Inventory Teleporting Back

### ISSUE THREAD

**Issue by MrVenenoZHacks** [ViaVersion/ViaBackwards#54] opened 2018-07-18 19:20 UTC
### What is the output url of /viaversion dump?
> 
https://dump.viaversion.com/9f1c1fe9e774c8924c16dab85db181a13aa42f777a62819f725c02b8a014f0dc
### How/when does this error happen? login?:
> 
When you want extract the items very fast from a chest or sometimes when you tried very slow is the same, the items back to chest, always is affected the version 1.11 and lower, like 1.10, 1.9, 1.8...
### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> No

**Comment by KennyTV** [comment] 2020-01-07 13:18
Closing this since this might or might not have been fixed in the last 2 years - if you find this issue to still exist and can show a little video of you reproducing it, we'll reopen it :)

**Closed by KennyTV** 2020-01-07 13:18 UTC
Labels: bug
