### ISSUE TITLE
ClientboundPlayerInfoUpdatePacket UPDATE_LISTED from 1.20 doesn't translate to 1.18

### ISSUE THREAD

**Issue by MCCasper** [ViaVersion/ViaBackwards#581] opened 2023-08-24 19:08 UTC
### '/viaversion dump' Output

Cannot provide as it contains NDA'd contents.

### Console Error

```
N/A.
```

### Bug Description

1.18 clients do not receive the player unlisting packet properly to remove them from tab on a 1.20 server. 

### Steps to Reproduce

1. Load a 1.20 server with ViaVersion and ViaBackwards
2. Create a plugin that sends a packet to the player updating the listed option in an entry with false.

### Expected Behavior

On a 1.20 client, the players are now not listed from the tab listing. On a 1.18 client, the player should also be hidden from the player. The 1.18 client currently does not hide the player.

### Additional Server Info

I run ViaVersion & ViaBackwards 4.7.1-SNAPSHOT. I run Paper build #160. Both jars for viaversion and viabackwards are from the direct CI.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-08-24 19:08
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by SplotyCode** [comment] 2023-09-08 14:28
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/510

**Closed** 2024-05-22 13:33 UTC
Labels: Feature Request
