### ISSUE TITLE
Dosen't work with 1.20 server

### ISSUE THREAD

**Issue by Harry-Jing** [ViaVersion/ViaBackwards#636] opened 2023-11-26 11:33 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/5422898178a8b980257ed019679fde63d76dc98ba32275d0f3ef75d6acb6d059

### Console Error

velocity console output:
    https://paste.gg/p/anonymous/f13688c84a1b49c58b962279e9b025d3

server console log:
```
[03:22:52] [Server thread/INFO]: com.mojang.authlib.GameProfile@79a8ae81[id=d817ce33-a305-3e6f-9054-3d1f5cb81f3c,name=HarryJing,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcwMDkwNDgzNjUwMiwKICAicHJvZmlsZUlkIiA6ICJmMzM5MjkyMzVkOTA0OGJmYjc3MDcyM2ZiNzhlYWQzNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJIYXJyeUppbmciLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzVhYzNjZDQ4MjdmYTgyZTFkNTcyNDQxZDY2NTQyMGEyNmE3MTllNTA4MjIxZWJiYWMyMjA2MjRjNTljZGU3OCIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjlhNzY1Mzc2NDc5ODlmOWEwYjZkMDAxZTMyMGRhYzU5MWMzNTllOWU2MWEzMWY0Y2UxMWM4OGYyMDdmMGFkNCIKICAgIH0KICB9Cn0=, signature=Le3UFURL3xN2soBTQ78NF2Ft040cRZLgX+4QrL4de4A2tVkySxCXLH8pIE8c1X/qmiHcJ+c9hrKeaNNhufi6PzVlTRvjwi8L6mDdK9AKiBy9hnIMF6WIwIz4iGsJLoTZv1i/Pb1XoqlyicHodBSBih9rQqgxs3U0YR2QrSA32N3Y9GQD0RnAkWTadGG9myGyGRnX6LkhPWVUErOtHRstSrIUueQ2FDNouxYSbo00KsX2eQ1hoO1R6C0VqohXQ3ylAD4PhuitSGwsxKXU9OhlCp2RC6knPelDbeySzvAzUuOIE3zF2yb+0jil5hjBbyimPrWAthrX65kWThGNjY3/0EwwhcsMyfkRPh47TM4IJ1A9SPRbsu2xi65za2Ml72Nho4t/bWNa26Ytzm2fAaEmdyk9YZ132UVGL56qcjbXc13da8cS+UoBqcdQvP5wSCTrpmXNBMOXaHh3dhYfvA2Qnau38so5TlPwwRgTjwnsxmXhvbqgIalcT+wEQ29aebWzzgwntfQr1dLssbZv+QE3NFkGPSW9zep7dptjRrSfofBoz21kstZ8LcTOtXRdHcAlr7uYx59NJ5qh4wyQcEEcnC+63Xa+yN+OO11NvpBhLS7QlkziLe9zmBmLUurZN9PlWMosSsNUbDU6GCFuDsdtvUlmxfnX1SjDzcyVzMKx23w=]]}] lost connection: Disconnected
```

### Bug Description

Can't use outher version client (I test for 1.18.2 fabric and 1.16.5 fabric) to connet a 1.20.2 server by installed in velocity

### Steps to Reproduce

Use a 1.18.2 client 

login to velocity server

stuck in `joining world...`
![image](https://github.com/ViaVersion/ViaBackwards/assets/69247286/95a83a59-ba5b-4ff2-947d-de31f1ffb8f7)

then show error `connection lost`
![image](https://github.com/ViaVersion/ViaBackwards/assets/69247286/3f9d3df6-9bbb-4762-bc69-ca7b52152802)

### Expected Behavior

I can join world

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-11-26 11:33
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Harry-Jing** [comment] 2023-11-26 11:40
https://dump.viaversion.com/9ec9cbaa016a7d9aa13a99067800d13a2d6df2520ada21bc3a2aba50922d93a4

**Comment by Barvalg** [comment] 2023-11-26 11:40
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-1.20.3-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--1.20.3--pre2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-1.20.3-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--1.20.3--pre1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Harry-Jing** [comment] 2023-11-26 11:41
linked issue: https://github.com/GeyserMC/Geyser/issues/4236

**Comment by Kichura** [comment] 2023-12-14 08:53
Duplicate of #642 as your issue is related to it.

**Closed by Kichura** 2023-12-14 08:53 UTC
Labels: unconfirmed
