### ISSUE TITLE
cant connect to my Survival server

### ISSUE THREAD

**Issue by JamesCzBestrunCZ** [ViaVersion/ViaBackwards#177] opened 2020-01-02 15:20 UTC
### What is the output url of /viaversion dump?
> We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/0d5b85af061336e57535a657ebbe470b967c73b9b76cdd34419d45d217e51fce

### How/when does this error happen? login?:
> When I join.

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Source #0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$1 (Anonymous), Data: [], Packet ID: 15}
Actual Error:
MrKubaCZ3 left the game

**Comment by Xernium** [comment] 2020-01-02 15:22
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/176#issuecomment-570205304

**Closed by Xernium** 2020-01-02 15:22 UTC

**Comment by JamesCzBestrunCZ** [comment] 2020-01-02 15:23
???

**Comment by JamesCzBestrunCZ** [comment] 2020-01-02 15:24
Pls help
