### ISSUE TITLE
Can't use 1.16+ protocols (ViaForge 1.8.9)

### ISSUE THREAD

**Issue by Aspw-w** [ViaVersion/ViaBackwards#552] opened 2023-06-08 16:02 UTC
### '/viaversion dump' Output

It's viaforge issue

### Console Error

Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.packets.EntityPackets1_16$3 (Anonymous)
Caused by: java.lang.NullPointerException

### Bug Description

https://github.com/ViaVersion/ViaForge/issues/64
see this

### Steps to Reproduce

1. Use the latest ViaForge 1.8.9, updated 20 hours ago on GitHub.
2. Select 1.16+ protocol to connect to the server.

### Expected Behavior

Can't connect server

### Additional Server Info

Every Servers (eu.loyisa.cn, minehut.com, cubecraft.net, etc...)

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Aspw-w** [comment] 2023-06-08 16:03
yes

**Comment by Kichura** [comment] 2023-06-08 16:08
Cannot reproduce your problem with this setup;

ViaFabric + ViaBackwards,
1.14.4 as client version.

**Comment by RaphiMC** [comment] 2023-06-08 16:13
Could not reproduce with this setup:

ViaProxy 3.0.19,
Vanilla 1.8.9 client,
1.20 server.

**Comment by FlorianMichael** [comment] 2023-06-08 16:19
Can you try to remove all your mods?

**Comment by FlorianMichael** [comment] 2024-02-01 13:52
Closing as outdated

**Closed by FlorianMichael** 2024-02-01 13:52 UTC
Labels: can't reproduce
