### ISSUE TITLE
DecoderException for FALLING_DUST particle in 1.9.4

### ISSUE THREAD

**Issue by Nubebuster** [ViaVersion/ViaBackwards#139] opened 2019-09-02 22:36 UTC
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/0175f36faa731d93b325feb5ad167e9931943b69dee2998452c2b7b278abe236

### How/when does this error happen? login?:
> when I send FALLING_DUST particle to some player

When a 1.9.4 player sees FALLING_DUST in a 1.12 server, they get kicked:
"Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/34 (gt) was larger than I expected, found 1 bytes extra whilst reading packet 34

And in 1.8.9 also:
"... 0/42 (gr) was larger, found 1 bytes extra ... packet 42

**Comment by Gerrygames** [comment] 2019-09-02 22:44
Duplicate of #44

**Closed by Gerrygames** 2019-09-02 22:44 UTC
