### ISSUE TITLE
[1.21.4 -> <1.19.1] Unable to join server by timed out connection.

### ISSUE THREAD

**Issue by leinzanne** [ViaVersion/ViaBackwards#941] opened 2024-12-19 17:10 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/f3c3898b1fc522b817595a1a30c4710c3e2c791cce55f85a73c0d58f5976f7dc

### Server/Client Error

https://mclo.gs/x5OUbKs

### Bug Description

Getting unable to join 1.21.4 -> <1.19.1

My server is hosted by Aternos and run with Fabric

Every time I run the game and join the sever on a version under 1.19.1, I get pointlessly timed out from the server. And it has no sense for me, because ViaVersion and ~Backwards were developed to accomplish this job over users.

I've tried everything. Reinstalling the server, deleting all mods unless ViaVersion ones, opening my client on Fabric instead of Vanilla, resetting player stats, regenerating the server world, almost everything I promise!

An extra point is that I trust ViaVersion, because it worked perfectly on other Aternos servers before. Better don't screw up this record.

I also need to know if this will lead to a fix I might wait for.

### Steps to Reproduce

1. Create an Aternos server with Fabric and game latest version.
2. Install ViaVersion mods (from ViaVersion and Backwards to ViaFabric and Fabric+).
3. Join the server under a 1.19.1 client.

### Expected Behavior

My goal is to being able to play the server in 1.16.5 because it's the most optimized version on my own, without doing technical stuff on the servers or in my client (like something under my acknowledgment reach) and without screwing up the server world.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2024-12-19 17:10
![Platform: 0.4.17+93--main](https://img.shields.io/badge/Platform-0.4.17+93--main-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.5-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.5--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment] 2024-12-19 17:12
This is a duplicate of #642, Though we have yet to see someone else write up a patch for the fabric servers.

**Closed by Kichura** 2024-12-19 17:12 UTC
Labels: unconfirmed
