### ISSUE TITLE
IllegalArgumentException: Legacy events must be single Component instances

### ISSUE THREAD

**Issue by ludgart** [ViaVersion/ViaBackwards#359] opened 2021-05-17 21:44 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/49043782cbed433e2a69a132d78ad327f8e3b79968d5de72555e4ecc3b437b4c

### Console Error

https://paste.gg/p/anonymous/9af403b3356541b991d4457a9846784b

### Bug Description

Random kick all players from the server

### Steps to Reproduce

/

### Expected Behavior

/

### Additional Server Info

1.16.5 paper
flamecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment] 2021-05-18 07:50
Can you download the latest ViaBackwards-DEV version and resend the error if it appears again? (This will print the error without kicking the players for now)

**Comment by ludgart** [comment] 2021-05-18 11:05
I cant re-test it, because of the issue from https://github.com/ViaVersion/ViaRewind/issues/314

**Comment by Xernium** [comment] 2021-05-18 15:20
I am just going to go ahead and say; if this is for the reason you’re personally offended because of the way we dealt with the mentioned issue then we can’t help you with this issue either.   
Please try to be professional about this, we do try our best too.
You aren’t entitled to our time nor do we have a claim to you reproducing this issue.
If you can’t replicate this issue because of a linked issue with modified clients then we can only treat this issue as invalid.
Take this also as a final warning; You want help from us and we are willing to help, so long as you do make an effort to actually be helpful.
There is no point in both parties wasting time in this. 
You have to understand that there are certain principles and rules that govern this project, and if you continue to argue with those then we will exclude you from our projects permanently.

**Comment by ludgart** [comment] 2021-05-18 17:18
Hello @Xernium,

I reported this bug to make this project better, but I can't retest it anymore.
I'm not creating a test server to test the newest build. I have no time and not the resources.
Furthermore, I am in no way offended. I'm just disappointed. 
I respect the work put into these projects. 
Calling Optifine a mod is technically right, but for the most players of Minecraft, it is just a normal client and should be respected. 
I'm not talking about Lunar or LabyMod. 
Threatening with a punishment is not the best way to handle issues. Apart from this, there is no rule information page.
But I think we can close this issue. Maybe someone else can test the newest build.

Regards
ludgart

**Comment by KennyTV** [comment] 2021-05-18 17:22
The new build hasn't "fixed" the issue, it just prevents players from being kicked over it, tho an exception will still be thrown. I wasn't able to reproduce this since testing complex component structures is always a bit finicky, so I'll have to wait for someone to run into this again to hopefully fix it more easily.

**Comment by kennytv** [comment] 2021-10-03 18:14
Should be fixed with https://github.com/ViaVersion/ViaVersion/commit/0a4d08886dc1e13b340d3de512f939c2093bfe1b

**Closed by kennytv** 2021-10-03 18:14 UTC
Labels: bug
