### ISSUE TITLE
1.9.4 - 1.13.2 clients crashes when right clicking to a NPC when teleporting to a minigame.

### ISSUE THREAD

**Issue by pabloalba16** [ViaVersion/ViaBackwards#403] opened 2021-10-16 10:16 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/9134391294a3ce6afb12f2de26a7ec70cbcb1baf2c256b34b7c4bd6f1020ab63

### Console Error

[12:08:29 ERROR]: [ViaVersion] An error occurred in metadata handler EntityPackets1_14 for PLAYER entity type: Metadata{id=12, metaType=VarInt, value=0}
[12:08:29 ERROR]: [ViaVersion] Full metadata: Metadata{id=0, metaType=Byte, value=0}
Metadata{id=1, metaType=VarInt, value=300}
Metadata{id=2, metaType=OptChat, value=null}
Metadata{id=3, metaType=Boolean, value=false}
Metadata{id=4, metaType=Boolean, value=false}
Metadata{id=5, metaType=Boolean, value=false}
Metadata{id=7, metaType=VarInt, value=0}
Metadata{id=8, metaType=Byte, value=0}
Metadata{id=9, metaType=Float, value=20.0}
Metadata{id=10, metaType=VarInt, value=8171462}
Metadata{id=11, metaType=OptPosition, value=null}
Metadata{id=11, metaType=Boolean, value=true}
Metadata{id=12, metaType=Float, value=0.0}
Metadata{id=12, metaType=VarInt, value=0}
Metadata{id=15, metaType=VarInt, value=258}
Metadata{id=16, metaType=Byte, value=0}
Metadata{id=17, metaType=Byte, value=1}
Metadata{id=18, metaType=NBTTag, value=CompoundTag { {} }}
Metadata{id=19, metaType=NBTTag, value=CompoundTag { {} }}
[12:08:29 WARN]: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class com.viaversion.viaversion.api.minecraft.Position (java.lang.Integer is in module java.base of loader 'bootstrap'; com.viaversion.viaversion.api.minecraft.Position is in unnamed module of loader 'ViaVersion-4.0.2-SNAPSHOT.jar' @43711a38)
[12:08:29 WARN]:        at ViaBackwards-4.0.2-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_13_2to1_14.packets.EntityPackets1_14.lambda$registerRewrites$7(EntityPackets1_14.java:460)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:118)
[12:08:29 WARN]:        at ViaBackwards-4.0.2-SNAPSHOT.jar//com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.handleMetadata(EntityRewriterBase.java:72)
[12:08:29 WARN]:        at ViaBackwards-4.0.2-SNAPSHOT.jar//com.viaversion.viabackwards.api.rewriters.LegacyEntityRewriter$3.lambda$registerMap$0(LegacyEntityRewriter.java:106)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[12:08:29 WARN]:        at ViaVersion-4.0.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[12:08:29 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor301.invoke(Unknown Source)
[12:08:29 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:08:29 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[12:08:29 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[12:08:29 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[12:08:29 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[12:08:29 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:08:29 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:08:29 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:08:29 WARN]:        at Vulcan-2.2.6.jar//io.github.repooper.packetevents.Vulcan_i.write(Vulcan_i.java:53)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:08:29 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:08:29 WARN]:        at WarpSystem_v5.0.5-free (1).jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:86)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:08:29 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:08:29 WARN]:        at WarpSystem_v5.0.5-free (1).jar//de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:86)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:08:29 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:08:29 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:08:29 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:08:29 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:450)
[12:08:29 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[12:08:29 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:08:29 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:08:29 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:08:29 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[12:08:29 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:08:29 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:08:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Bug Description

I'm running Purpur 1.17.1 with the latest version of ViaVersion, ViaBackwards and ViaRewind of jenkins. Apparently, 1.9.4 - 1.13.2 minecraft clients crashes when you rightclick a NPC that has a running command on it, making the teleport but instantly crashing. This issue does not happen in 1.14+

### Steps to Reproduce

Create a 1.17.1 purpur server with ViaVersion and its addon ViaBackwards and put Citizens2 (latest jenkins version) with CommandNPC plugin: https://www.spigotmc.org/resources/commandnpc.40295/ Add an NPC with an executable command by doing /npc cmdadd warp SkyWars (for example). You should get the error.

### Expected Behavior

To not crash the client

### Additional Server Info

My plugin list (if that helps)
![image](https://user-images.githubusercontent.com/49927979/137583617-8a29b4e3-b0cb-45f9-869d-a85d06135e93.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment] 2021-10-16 10:38
Can't reproduce. Please try without other plugins aside from Via, the npc plugins, and the warp plugin.

**Comment by pabloalba16** [comment] 2021-10-16 10:54
Just tested and doesnt happen so, maybe another plugin is causing the issue?

**Comment by pabloalba16** [comment] 2021-10-16 11:00
I found the issue, was my anticheat

**Comment by kennytv** [comment] 2021-11-13 17:05
Closing in favor of a duplicate with a better description https://github.com/ViaVersion/ViaBackwards/issues/408

**Closed by kennytv** 2021-11-13 17:05 UTC
Labels: unconfirmed
