### ISSUE TITLE
Console Spam regarding - Stored entity with id -1 not found!

### ISSUE THREAD

**Issue by D3monw3st** [ViaVersion/ViaBackwards#173] opened 2019-12-16 19:06 UTC
### What is the output url of /viaversion dump?
> https://dump.viaversion.com/d311f979b9ce44b9c1410a4702f94b4f6b92144a8ba8204e8f9c8b9e04a3bfa7

### How/when does this error happen? login?:
> This occurs upon the login of the user. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> 
https://pastebin.com/yPzYhTdZ

**Comment by KennyTV** [comment] 2019-12-16 19:15
Do you have any plugins spawning custom entities (via packets)?

**Comment by D3monw3st** [comment] 2019-12-16 19:20
Hi Kenny, 

I don't have any plugins that would spawn custom entities. The only thing that I could think of would be Holographic Displays. I did disable plugins individually and the only interesting thing that I had found was this:

`[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:14] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id -1 not found!
[11:19:15] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id 69 not found!
[11:19:16] [Server thread/INFO]: D3monw3st issued server command: /plugman unload HolographicDisplays
[11:19:16] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.4.0
[11:19:16] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id 69 not found!
[11:19:18] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id 69 not found!
[11:19:21] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id 70 not found!
[11:19:21] [Netty Server IO #0/WARN]: [ViaBackwards] Stored entity with id 73 not found!`

**Comment by KennyTV** [comment] 2019-12-16 19:25
Can you try fully restarting the server with/without Citizens/HD?

**Comment by D3monw3st** [comment] 2019-12-16 19:55
I've booted with and without Citizens through a full restart and the error still appeared.

**Comment by KennyTV** [comment] 2019-12-16 20:00
Added an extra bit of information in that warning in the last abstraction build, but in general there should never be an entity with the id of -1 🤔

**Comment by D3monw3st** [comment] 2019-12-16 20:00
When I disabled Holographic displays while disabling every plugin 1 at a time, it stopped. When I removed HD displays from the plug list and rebooted, the ID numbers changed but the issue still prevailed.

**Comment by D3monw3st** [comment] 2019-12-16 20:01
It appears that this only occurs when you join on 1.8.9 or below, I was just testing out since players are not very reliant to switch off of 1.8.9 to make sure everything is working as intended when this bug appeared.

**Comment by iamharak** [comment] 2019-12-17 17:28
I have the same issue.
The log is spammed with thousands of these lines: 
```
[18:10:34 WARN]: [ViaBackwards] Stored entity with id 1029 not found in packet 50
[18:10:34 WARN]: [ViaBackwards] Stored entity with id 1035 not found in packet 50
[18:10:35 WARN]: [ViaBackwards] Stored entity with id 1029 not found in packet 50
[18:10:35 WARN]: [ViaBackwards] Stored entity with id 1035 not found in packet 50
[18:10:36 WARN]: [ViaBackwards] Stored entity with id 1029 not found in packet 50
[18:10:36 WARN]: [ViaBackwards] Stored entity with id 1035 not found in packet 50
[18:10:36 WARN]: [ViaBackwards] Stored entity with id 1029 not found in packet 50
[18:10:36 WARN]: [ViaBackwards] Stored entity with id 1035 not found in packet 50
[18:10:37 WARN]: [ViaBackwards] Stored entity with id 1029 not found in packet 50
[18:10:38 WARN]: [ViaBackwards] Stored entity with id 1029 not found in packet 50
[18:10:38 WARN]: [ViaBackwards] Stored entity with id 1035 not found in packet 50
[18:10:39 WARN]: [ViaBackwards] Stored entity with id 1023 not found in packet 50
[18:10:39 WARN]: [ViaBackwards] Stored entity with id 1029 not found in packet 50
[18:10:39 WARN]: [ViaBackwards] Stored entity with id 1032 not found in packet 50 
```

**Comment by KennyTV** [comment] 2019-12-17 17:49
Ngl no idea why this happens - could someone try this version (which adds x,y,z debug), teleport to the given coordinates and tell me what entities are affected? 👀
[viabackwards-teleport-debug.zip](https://github.com/ViaVersion/ViaBackwards/files/3974644/viabackwards-teleport-debug.zip)

**Comment by iamharak** [comment] 2019-12-18 12:55
Hey. I just tested the debug version of ViaBackwards that you've sent me yesterday. For the sake of testing, I removed Holographicdisplays and Citizens to see if they cause any issues. The answers is yes, they cause. At least Citizens. It looks like the problem is caused by those npc-s that Citizens spawns (btw all the coordinate-s in the error messages pointed to these locations too).

The issue is only present on 1.13.2 and below.

Server version: 1.14.4 [Paper-237]
Via plugin versions: ViaVersion-abstraction, ViaBackward-abstraction (debug), ViaRewind-DEV.


![2019-12-18_12 13 02](https://user-images.githubusercontent.com/39100142/71088009-c2ccb880-219d-11ea-9444-ab0a35dc649d.png)
![2019-12-18_12 13 24](https://user-images.githubusercontent.com/39100142/71088011-c3654f00-219d-11ea-8ea1-936c76945810.png)
![2019-12-18_12 13 36](https://user-images.githubusercontent.com/39100142/71088012-c3654f00-219d-11ea-8582-83f6791ca768.png)
![2019-12-18_12 13 56](https://user-images.githubusercontent.com/39100142/71088014-c3654f00-219d-11ea-9338-22981a62a4f9.png)
![2019-12-18_12 14 26](https://user-images.githubusercontent.com/39100142/71088015-c3654f00-219d-11ea-951a-7ab7943a6563.png)

**Comment by KennyTV** [comment] 2019-12-18 13:04
Do the y coordinates match the npc's position or that of the hologram?

**Comment by iamharak** [comment] 2019-12-18 13:07
The coordinates point to the NPCs.

**Comment by D3monw3st** [comment] 2019-12-18 18:35
[10:34:57] [Netty Server IO #2/WARN]: [ViaBackwards] Stored entity with id -1 at position: 0.0 - 0.0 - 0.0
                                                                                                                 
This is what I'm getting...

**Comment by KennyTV** [comment] 2019-12-18 18:37
@D3monw3st Looks like one of your plugins is doing something it definitely shouldn't be doing - try removing plugins until you find the one that is causing this.
To iamharak: Thanks, I'll try to find if the cause is on our end when I have the time

**Comment by D3monw3st** [comment] 2019-12-18 18:37
> @D3monw3st Looks like one of your plugins is doing something it definitely shouldn't be doing - try removing plugins until you find the one that is causing this.
> To iamharak: Thanks, I'll try to find if the cause is on our end when I have the time

Hi Kenny,
I've already removed the plugins one by one, when I tp'd to the coordinates using the vanilla-based command /tp x y z the bugs stopped.

**Comment by KennyTV** [comment] 2020-01-02 17:11
Alright, so here's what I found: The -1 is 100% something the plugin should never do, so that's worthy of a report there (afaik it was HD?).

The other warnings for positive ids are teleport/metadata packets for npcs that are actually outside of the range of the player - which means they are sending teleport packets for untracked entities. This can also be fixed by the plugin in question, tho it doesn't do any harm to the server or client, so you're still fine with setting `suppress-metadata-errors` to `true` in the Via config to just disable the warnings.
Case closed 🌂

**Closed by KennyTV** 2020-01-02 17:11 UTC
