### ISSUE TITLE
can't connect 1.20 to 1.20.2 server

### ISSUE THREAD

**Issue by SyedOmarNoor** [ViaVersion/ViaBackwards#631] opened 2023-11-12 10:15 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/62177b9a8cb5a559ad4eebca90a4daad4aea641e64a8a22f4b5afc5c84b0e506

### Console Error

in server log
```
[21:02:02] [User Authenticator #1/INFO]: UUID of player MLGDankLord2121 is 631ae4a5-6294-4726-ae4f-068f186196f0
[21:02:02] [Server thread/INFO]: com.mojang.authlib.GameProfile@1617e9ee[id=631ae4a5-6294-4726-ae4f-068f186196f0,name=MLGDankLord2121,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTY5OTc4MzMyMjU4MywKICAicHJvZmlsZUlkIiA6ICI2MzFhZTRhNTYyOTQ0NzI2YWU0ZjA2OGYxODYxOTZmMCIsCiAgInByb2ZpbGVOYW1lIiA6ICJNTEdEYW5rTG9yZDIxMjEiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZhY2QwNmU4NDgzYjE3NmU4ZWEzOWZjMTJmZTEwNWViM2EyYTQ5NzBmNTEwMDA1N2U5ZDg0ZDRiNjBiZGZhNyIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9, signature=f+y1+8tRFLE3hDaE9oBmPc4CgvTsBi2FJoQ5Fw/PWu0TGvghfljuGYV/yMZxDaqZDZsdJrS1SzmQuVBn3004bkfrsDBGbzyyMjFZlP88+Sk8OP9qJh/FWxTGIXR4tvWXte7GFuFqFsnFxcsDQH06TOJ24Ug2DTCeKxWCA0YDjEfCNPgFBFa7m/XL/C2N8u0lsd8/b9odW9Txyc/2ek2+nUF/Rj6G+3MrTL7rL0xk13QCXWLRDjUSmBA2TVhgz/12+0e7o9XZxXJb8F7hQ9AFNtYVKfq8+qFC0H1yMoRRIiaTIvMW4dt4OpEkCaLxYMrbtdrmzLcRB8xQnKw8hS4urHSoblg+NFE9YoiEpCAwAlFPQSYmX3WX6ty/mSiysP7fupNNdOhWNtEia+1YJZprP/TWWck1IT+x1AOHlnHLxJOOboMGXErKQ1lxLMCBa0ZholikgGSeWQw1+3hwLimxs+bLo+FdqAOzy9+6aeB2DoP8MRtlVu+cKgiM0CssZ4AyUNHZUwjaWitksRuTAtvMIgmaVtAeLL6bb6x4qMODUeiZJp96cagvJjyhBxokJIF9tOXidhuUqhBkrUmGngPN5sCbndE/WOw2un0ZMgshIU4vjyh0LSDm43gwC82py5hdjhLIrnHsfR/+psAYgl9x4p5WckMiiMfJqu/D5knLAGE=]]}] lost connection: Disconnected
```
in client 1.20 vanilla
```
Internal Exception: io.netty.handler.codec.decoderexception: the received encoder string buffer length is longer than maximum allowed (465914>98301)
```

### Bug Description

can't join 1.20 vanilla to 1.20.2 fabric server (removed all mods and now have only fabricapi, viafabric and viabackwards)

i can join 1.20.2 fine to 1.20.2 server

### Steps to Reproduce

1. create 1.20.2 with fabric 1.20.2 loader 0.14.24
2. install fabricapi as well as viafabric and viabackwards in mods folder
3. join using any version reasonably below 1.20 (same error with 1.20.1 and 1.20, 1.8.9 said 1.20.2X so no error might just need viarewind if i wanted to support that)

### Expected Behavior

it should connect without any error

### Additional Server Info

- minecraft 1.20.2 server
- fabric 0.14.24
- fabric api 0.90.7 (1.20.2)
- viafabric 0.4.11+46 (contains viaversion 4.8.1)
- viabackwards 4.8.1
client is microsoft store java 1.20

i removed all other mods i had before and problem persists, im assuming it's something to do with viabackwards since that's the main thing that changed and also since i can still connect with 1.20.2 fine

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists. (i can't do this since viafabric isn't there however i need it to be checked so i can post it)

**Comment by destroyfish** [comment] 2023-11-12 12:29
I have the same issue as you, following this. I am using spigot, and trying to join with 1.20.1 with optifine and forge. It must be an issue with the Java Versions because I can join easily with 1.20.2 forge, but 1.19 and 1.20 (versions i tested so far) are getting me that string error.

**Comment by Kichura** [comment] 2023-11-12 12:30
Fabric API issue, although this issue is still ongoing.

**Comment by Kichura** [comment] 2023-11-12 12:32
Also going to close this as this is technically a dupe of [ViaFabric's #275](https://github.com/ViaVersion/ViaFabric/issues/275).

**Closed by Kichura** 2023-11-12 12:32 UTC
Labels: unconfirmed
