### ISSUE TITLE
Disconnect on Player.sendTitle();

### ISSUE THREAD

**Issue by CCCoderDE** [ViaVersion/ViaBackwards#217] opened 2020-06-30 14:56 UTC
**Describe the bug, provide any errors**
The Client disconnects after a Plugin calles [Player.sendTitle();](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#sendTitle-java.lang.String-java.lang.String-int-int-int-)

**How can we reproduce it?**
1. Login with 1.9 client on 1.15.2 server
2. Do anything to make your custom Plugin call the method above
3. The client is disconnected with the error message shown in the picture: [Disconnect Screen](http://prntscr.com/t97sck)

**Expected behaviour**
The client to stay connected and the title to be shown correctly

**Screenshots**

**ViaVersion Dump:**
- [Dump](https://dump.viaversion.com/8bc6def1d4fa4f93e1de48d9828090bfd9c83e80e30ddabe14a5d702be638cdb)

**Additional server info**
BungeeCord (1.16), Spigot (1.15.2), Custom Spigot-Plugin to call sendTitle

**Comment by CCCoderDE** [comment] 2020-06-30 14:58
Just to clarify: My custom Plugin on its own has nothing to do with this error. When I comment out the line that calls sendTitle, everything works :)

**Comment by KennyTV** [comment] 2020-06-30 15:10
What is the actual content of the title?

**Comment by CCCoderDE** [comment] 2020-06-30 15:11
`§a§l-= §2§4CCCoder's§2 Island§a§l =-`

**Comment by CCCoderDE** [comment] 2020-06-30 15:13
Also, I just noticed that the title is shown when I reconnect, independent of which server I connect to.. So when I get disconnected from my server because of this and then I connect to some other server (or my server again), the title which caused the disconnect is shown

**Comment by KennyTV** [comment] 2020-06-30 15:15
Try the latest builds from ci.viaversion.com please, I can't reproduce your issue locally

**Comment by CCCoderDE** [comment] 2020-06-30 15:19
Still getting the same error [Dump](https://dump.viaversion.com/4f4855b4b65e52970381ea862fb96011f7026b16f82082e6812a585cb4c0911e)

**Comment by CCCoderDE** [comment] 2020-06-30 15:19
Also, I set the content of the Title to "test", but that didn't change anything either

**Comment by KennyTV** [comment] 2020-07-01 07:47
Try again without other plugins on both proxy and backend, and paste the concrete sendTitle call in here

**Comment by CCCoderDE** [comment] 2020-07-06 11:44
Downloaded the latest versions from CI again. I'm still getting disconnected.

The exact call is:

`player.sendTitle("§a§l-= §2" + this.getIslandName() + "§a§l =-", "", 10, 70, 20);`

`this.getIslandName()` returns `§4CCCoder's§2 Island` in this scenario

**Comment by KennyTV** [comment] 2020-07-06 12:57
Fixed with the next relase :)

**Closed by KennyTV** 2020-07-06 12:57 UTC
