### ISSUE TITLE
1.12.2 ViaBackwards "Timed Out" bug.

### ISSUE THREAD

**Issue by OmegaByte** [ViaVersion/ViaBackwards#215] opened 2020-06-29 22:36 UTC
**Describe the bug, provide any errors**
When players try to open ender chests with Shulkers named with special characters or with items with special characters, or open Shulkers with special characters or items with special characters they get this weird bug were they can't do anything for like 10-15 seconds, other players see them not moving but they can do actions or move, and then they get kicked for "Timed out". This only happens for the version 1.12.2, I haven't tested it on 1.13, in 1.14.4 doesn't happen.

**How can we reproduce it?**
1. Login on 1.12.2'
2. Make a shulker kit, or some shulker kits with special characters inside them, or shulker renamed with special characters.
3. Put the shulker/s inside an Ender Chest
4. Open the enderchest, and you wouldn't be able to make any actions for like 10-15 seconds
5. Then you would be kicked for Timed Out.

**Expected behaviour**
The player needs to open the shulker or ender chest and it shouldn't say '{"extra":[{"text:"Incursionaire\u0027s Wings"}],"text":""} x1 when an Item is renamed with special characters, also when a player opens his ender chest or shulker with this special character it shouldn't time out them.

**Screenshots**
![Screenshot_117](https://user-images.githubusercontent.com/58628812/86061777-5f1d2500-ba35-11ea-86d4-db58fd645cf5.png)

**ViaVersion Dump:**
https://dump.viaversion.com/83394601f8ab2246bed65188aa6f11960cedc643c41444acea909e999c8c75f4

**Additional server info**
I use FlameCord as my proxy, and Tuinity as my jar. The ViaVersion and ViaBackwards plugins are in my Tuinity 1.15.2 server.

**Comment by KennyTV** [comment] 2020-06-30 07:11
\u0027 is a standard `'`, so no idea who/where it's set with the escaped code. The wrong display of the name is a won't fix, since it would possibly require heavy operations with all chests and especially shulker boxes.
Unless you can reproduce this on a clean Paper server without any other plugins, I doubt this is a Via issue.

**Closed** 2020-07-18 10:04 UTC
