### ISSUE TITLE
Internal Exception, Index out of bounds

### ISSUE THREAD

**Issue by LoosiusGoosius** [ViaVersion/ViaBackwards#610] opened 2023-10-12 00:04 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/c3c09c4821f663cd541ffd30d4cdf95ebd48be3b18f5e9d2c4b233f243370b5b

### Console Error

1.20.2 Server https://mclo.gs/7763xvt
First join is vanilla 1.20.2 (success)
Second join is forge 1.20.2 (success)
Third join is vanilla 1.19.2 (failure)
Fourth join is forge 1.20.1 (failure)
Fifth join is second account, vanilla 1.20.1 (failure)

### Bug Description

Joining server on anything other than 1.20.2 throws the error "Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 64 out of bounds for length 5"
Have tried with a fresh environment, fresh install of purpur 2078, only ViaVersion 914 and ViaBackwards 518. Have tested from multiple accounts. Have had other people test from their accounts. 

### Steps to Reproduce

1. Start 1.20.2 Purpur server with only ViaVersion 914 and ViaBackwards 518
2. Attempt to join with anything other than 1.20.2, forge and fabric do not seem to matter
3. Returned with Internal Exception

### Expected Behavior

Successfully join the server with anything other than 1.20.2

### Additional Server Info

I use Purpur build 2078, as of right now no additional plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2023-10-12 00:04
![Platform: git--Purpur--2078%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2078%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment] 2023-10-12 01:06
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/607

**Closed by kennytv** 2023-10-12 01:06 UTC
Labels: unconfirmed

**Comment by kennytv** [comment] 2023-10-12 01:11
Anything else you can tell us about the setup, like whether you use a resource pack, a proxy, or some ddos protection layer that might interfere with packets?

**Comment by LoosiusGoosius** [comment] 2023-10-12 01:32
Wanted to update, I hadn't even thought of the resource pack causing an issue. I had just updated it, but removed it and restarted the server and it seems to be working, Apologies for the inconvenience.
