### ISSUE TITLE
Players can """break""" blocks in worldguarded area to glitch through in 1.18.x

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaBackwards#688] opened 2024-02-20 18:40 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/b59608e48d5233b01ff3419bb5e0906f1b9f13980c4791b19c3e626440f29988

### Console Error

*(No console errors have been found)*

### Bug Description

When worldguarding any blocks using admin commands such as cobwebs, Players on 1.18.x clients can use anything to """break""" the blocks to get past even though they are protected in first place - This never occurs on 1.19 and onwards including earlier clients.

### Steps to Reproduce

1. Obtain the latest builds of ViaVersion and ViaBackwards,
2. Obtain both WorldEdit and WorldGuard for the 1.20.4 server,
3. Place 4 cobwebs in one spot and worldguard them,
4. Have another player attempt to break them on any 1.18.x client,
5. Notice they can walk through without any speed penalty.

### Expected Behavior

Players cannot break any blocks that are worldguarded.

### Additional Server Info

1. This server does not use any proxies,
2. This server uses git-Paper-430 *(1.20.4)*,
3. The following plugins were used:

ViaBackwards 4.10.0-SNAPSHOT,
ViaVersion 4.10.0-SNAPSHOT,
WorldEdit 7.2.20-SNAPSHOT,
WorldGuard 7.0.10-SNAPSHOT.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2024-02-20 18:40
![Platform: git--Paper--430%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--430%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w07a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w07a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w07a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w07a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment] 2024-03-04 11:12
Update on this: This also breaks WorldEdit's left-clicking mechanic using the wand aswell when playing on 1.18.2 and older while the player is an server operator themselves.

**Comment by kennytv** [comment] 2024-05-05 10:52
Duplicate of https://github.com/ViaVersion/ViaBackwards/issues/688

**Closed by kennytv** 2024-05-05 10:52 UTC
Labels: bug
