### ISSUE TITLE
Inventory Re-ordering Bug on 1.17.1

### ISSUE THREAD

**Issue by blockswerker** [ViaVersion/ViaBackwards#409] opened 2021-11-14 17:35 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/ad49ff0f74e32fd4bef70115cb67fd80454dc9d64a14fbafdf7fb3ece8f8c8a8

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

When re-ordering items in player inventory the items appear to duplicate, appearing for 2-3 seconds in both the original and new inventory slot. After 2-3 seconds the inventory updates, usually cancelling the re-ordering action.

Server is running Paper 1.17.1 #381 but occurs on older builds. Client is 1.12 or 1.16.5 (have not tried other versions). Does not occur using 1.17.1 client.

Video:
https://streamable.com/i6ijtd

### Steps to Reproduce

1. Login with 1.16.5 client in Survival Mode.
2. Re-arrange items in inventory.

### Expected Behavior

Re-arranging items should match 1.17.1 behavior. No item duplicating or ghost items should occur.

### Additional Server Info

Paper 1.17.1 #381
No BungeeCord
LuckPerms
ViaVersion
ViaBackwards

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment] 2021-11-14 17:35
![Platform: git--Paper--381%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--381%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 58 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-58%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.0.1): 18 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment] 2021-11-14 17:37
Related to/duplicate of https://github.com/ViaVersion/ViaBackwards/issues/389

**Closed by kennytv** 2021-11-14 17:37 UTC
Labels: unconfirmed
