### ISSUE TITLE
1.20.1 and below can't place certain blocks

### ISSUE THREAD

**Issue by Folas1337** [ViaVersion/ViaBackwards#732] opened 2024-04-29 18:26 UTC
### '/viaversion dump' Output

https://dump.viaversion.com/512fd7bc993150d868610e0bdab554b2432b77c280908470a374ec4b47724ef9

### Console Error

There is none

### Bug Description

If I run ViaVersion on velocity and a paper backend and velocity only has ViaVersion and ViaBackwards installed and the paper backend has no plugins installed and I join with version 1.20.1 or lower, I can not place certain blocks such as:
- Andesite Stairs
- Andesite Walls

I haven't tested much more but a user just reported this and I was able to consistently and very easily reproduce it on my local computer.

### Steps to Reproduce

1. Launch a new paper server with 1.20.4
2. Launch a velocity proxy with ViaVersion and ViaBackwards installed
3. Join with a client version 1.20.1
4. Get an andesite stair or andesite wall and try to place it

### Expected Behavior

The blocks should be placed but they vanish within a split second and once you rejoin, they're gone from your inventory

### Additional Server Info

All stated above

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Folas1337** [comment] 2024-04-29 18:31
https://dump.viaversion.com/d3fa138ffd96706c7e2e8fc260e850963df0d6749c3a2608cdb1fafe70ee63c8

I can't download any more recent Via* plugins.

**Comment by Barvalg** [comment] 2024-04-29 18:31
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--a9a31f69--b385%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--a9a31f69--b385%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Ceddix** [comment] 2024-05-04 17:48
Which blocks exactly? I have the same issue with **Chiseled Stone Bricks**.
Happens in 1.20.1 or lower and people cannot place them (_sometimes_) and they just disappear, also on teleports (_sometimes_).

**Comment by Folas1337** [comment] 2024-05-04 17:55
> Which blocks exactly? I have the same issue with **Chiseled Stone Bricks**. Happens in 1.20.1 or lower and people cannot place them (_sometimes_) and they just disappear, also on teleports (_sometimes_).

As step 4 says, I was able to verify it with these: "Get an **andesite stair** or **andesite wall** and try to place it"

**Comment by Kichura** [comment] 2024-05-04 18:06
Can reproduce.

**Comment by explor4268** [comment] 2024-05-05 04:36
Can reproduce it since updating **ViaVersion** from **4.9.3** into **4.10.0**, and **ViaBackwards** from **4.9.2** into **4.10.0**

**Comment by kennytv** [comment] 2024-05-05 12:41
Fixed in https://github.com/ViaVersion/ViaVersion/commit/f1b92fea8d59ffdf7b32ac6213de78c72b5d1238

**Closed by kennytv** 2024-05-05 12:41 UTC
Labels: bug

**Comment by Barvalg** [comment] 2024-05-05 14:41
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
